### ISSUE TITLE
Getting duplicate values for USDC.e on UI when starting AMM-arbitrage strategy

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#144] opened 2023-07-03 13:39 UTC
**Describe the bug**
Observed when checking `USDC.e` supported connectors the UI returns two tokens with same value when starting the AMM-Arbitrage strategy. This happened for both `avalanche (traderjoe, pangoln)` and `uniswap (arbitrum_one)` when we initially setup the `gateway connector-token` command with a set of tokens that would display on `balance` command

![image](https://github.com/hummingbot/gateway/assets/73840223/9c9b1fd2-f394-4813-a594-0af895b78c10)

**Steps To Reproduce**
1. Setup latest development client and gateway
2. Setup connector-token command and add USDC.e or USDC.E
3. Setup amm-arb with avalanche or uniswap arbitrum_one connector
4. Observe the display balance upon starting the amm-arb

**Release version**
development 1.18.0 (gateway+client)

**Attachments**
no logs needed

**Comment by fengtality** [comment] 2023-07-05 20:17
## Bounty

* Sponsor: Hummingbot Foundation
* Budget: [HGP-26](https://snapshot.org/#/hbot.eth/proposal/0x7a02f532e0452d3ce7f8b64a8a52e6bed285cc65461a1523fa0f91f2024f8c01)
* Classification: P3
* Bounty: 10,000 HBOT
* Developer share: 100% - paid upon merge to development
* Status: OPEN

**Comment by isreallee82** [comment] 2023-07-27 02:24
I got a fix for this and gateway#143 as they are related can you assign

**Comment by isreallee82** [comment] 2023-07-27 03:55
In no case you should use USDC.E as it worked as a result of bug causing the duplicate on the ui, 

- **fix** 

** after the latest merge for commit **

- you should remove USDC.E if added

- [ ] Setup connector-token command and add USDC.e or USDC.E ❌

then

- [ ] Setup connector-token command and add USDC.e ✅
- [ ] Setup amm-arb with avalanche or uniswap arbitrum_one connector ✅
- [ ] Observe the display balance upon starting the amm-arb ✅

I pushed to development as it should fix gateway - Uniswap unhandled error #143 also #

**Comment by nikspz** [comment] 2023-08-24 07:18
![image](https://github.com/hummingbot/gateway/assets/83953535/231f28f2-e178-458a-8377-20cbd4676a6c)
Closing this issue and Bounty as can't reproduce

**Closed by nikspz** 2023-08-24 07:18 UTC
Labels: bug, P3, bounty
