### ISSUE TITLE
V1.13 Install from source Gateway uniswap polygon nonce issue

### ISSUE THREAD

**Issue by toxicehc** [hummingbot/gateway#61] opened 2023-03-15 03:53 UTC
Clean install from source cannot execute any transactions.

It kicks out this error on every single transaction:
2023-03-15 11:37:00 | info |    Expected execution price is 0.047863, limit price is 0.047575326988000. | undefined
2023-03-15 11:37:00 | info |    Providing the next nonce 258 for address[masked]. | undefined
2023-03-15 11:37:00 | error |   Transaction with nonce 258 for address [masked] failed : Error: replacement fee too low [ See: https://links.ethers.org/v5-errors-REPLACEMENT_UNDERPRICED ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":35700,\"error\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",

checking on oklink in the mempool there is no such nonce txn. Previous txn was 257.

Running a simple AMM ARB between HUOBI and Uniswap Polygon

Here are the steps to reproduce the issue (see attachments in the section below):
1. Clean install V1.13 from Source
2. Clean install Gateway from Source

**Screenshots**
![image](https://user-images.githubusercontent.com/4660657/225201918-f8d4ca53-562b-405f-b328-42bb665d4285.png)

**Release version**
V1.13

**Optional: your discord username:**
toxicehc#5599

**Comment by nikspz** [comment] 2023-03-15 10:58
Hey @toxicehc Could you tell the what polygon nodeURL and your trading pair that you use?

**Comment by nikspz** [comment] 2023-03-15 11:31
@toxicehc hmm strange that it works now on v1.12, I'll try to reproduce

**Comment by nikspz** [comment] 2023-03-15 11:33
Yep logs/config files should help

**Comment by toxicehc** [comment] 2023-03-15 11:40
[logs_conf_amm_arb_1.log](https://github.com/hummingbot/gateway/files/10979155/logs_conf_amm_arb_1.log)
[logs_hummingbot.log](https://github.com/hummingbot/gateway/files/10979157/logs_hummingbot.log)
[logs_gateway_app.log.2023-03-14.log](https://github.com/hummingbot/gateway/files/10979158/logs_gateway_app.log.2023-03-14.log)
[conf_amm_arb_1.yml.log](https://github.com/hummingbot/gateway/files/10979166/conf_amm_arb_1.yml.log)
[uniswap.yml.log](https://github.com/hummingbot/gateway/files/10979167/uniswap.yml.log)

Here you go :)

**Comment by fengtality** [comment] 2023-03-15 19:17
> So looks like it does not like chainstacklabs

Your node connection is very important in using Gateway. I've seen huge differences across different node providers on different chains and networks. It's also dynamic since market conditions and random outages also affect the experience.

We're evaluating how to make this more transparent to users and allow them to switch providers more easily.

**Comment by fengtality** [comment] 2023-03-15 19:19
Closing this as it appears this is an issue with the user's node provider.

**Closed** 2023-03-15 19:19 UTC
